node {
    def app

    stage('Clone repository') {
       checkout scm
    } 
    stage('Generate Jar Package') {
            dir("/var/lib/jenkins/workspace/New_demo/my-app/") {
                    sh 'cd my-app'
                    sh 'mvn -B -DskipTests clean package'
            } 
    }   
}